import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedPlatforms() {
  console.log('🚚 Seeding delivery platforms...');

  const platforms = [
    {
      name: 'Instacart',
      slug: 'instacart',
      type: 'grocery',
      logo: '/platforms/instacart.png',
      website: 'https://www.instacart.com',
      apiEnabled: true,
      appScheme: 'instacart://',
      iosAppId: '545599256',
      androidPackage: 'com.instacart.client',
      deliveryFeeMin: 3.99,
      deliveryFeeMax: 9.99,
      serviceFeePercent: 5.0,
      minimumOrder: 10.00,
      active: true,
    },
    {
      name: 'Uber Eats',
      slug: 'uber-eats',
      type: 'both',
      logo: '/platforms/uber-eats.png',
      website: 'https://www.ubereats.com',
      apiEnabled: false,
      appScheme: 'ubereats://',
      iosAppId: '1058959277',
      androidPackage: 'com.ubercab.eats',
      deliveryFeeMin: 0.99,
      deliveryFeeMax: 7.99,
      serviceFeePercent: 15.0,
      minimumOrder: 12.00,
      active: true,
    },
    {
      name: 'DoorDash',
      slug: 'doordash',
      type: 'both',
      logo: '/platforms/doordash.png',
      website: 'https://www.doordash.com',
      apiEnabled: false,
      appScheme: 'doordash://',
      iosAppId: '719972451',
      androidPackage: 'com.dd.doordash',
      deliveryFeeMin: 1.99,
      deliveryFeeMax: 8.99,
      serviceFeePercent: 11.0,
      minimumOrder: 10.00,
      active: true,
    },
    {
      name: 'Grubhub',
      slug: 'grubhub',
      type: 'restaurant',
      logo: '/platforms/grubhub.png',
      website: 'https://www.grubhub.com',
      apiEnabled: false,
      appScheme: 'grubhub://',
      iosAppId: '302920553',
      androidPackage: 'com.grubhub.android',
      deliveryFeeMin: 0.00,
      deliveryFeeMax: 6.99,
      serviceFeePercent: 10.0,
      minimumOrder: 12.00,
      active: true,
    },
    {
      name: 'Postmates',
      slug: 'postmates',
      type: 'both',
      logo: '/platforms/postmates.png',
      website: 'https://www.postmates.com',
      apiEnabled: false,
      appScheme: 'postmates://',
      iosAppId: '512393983',
      androidPackage: 'com.postmates.android',
      deliveryFeeMin: 1.99,
      deliveryFeeMax: 9.99,
      serviceFeePercent: 12.0,
      minimumOrder: 0.00,
      active: true,
    },
    {
      name: 'Shipt',
      slug: 'shipt',
      type: 'grocery',
      logo: '/platforms/shipt.png',
      website: 'https://www.shipt.com',
      apiEnabled: false,
      appScheme: 'shipt://',
      iosAppId: '1056683515',
      androidPackage: 'com.shipt.app',
      deliveryFeeMin: 0.00,
      deliveryFeeMax: 7.99,
      serviceFeePercent: 0.0, // Membership-based
      minimumOrder: 35.00,
      active: true,
    },
    {
      name: 'Amazon Fresh',
      slug: 'amazon-fresh',
      type: 'grocery',
      logo: '/platforms/amazon-fresh.png',
      website: 'https://www.amazon.com/fresh',
      apiEnabled: true,
      appScheme: 'amazon://',
      iosAppId: '297606951',
      androidPackage: 'com.amazon.mShop.android.shopping',
      deliveryFeeMin: 0.00,
      deliveryFeeMax: 9.95,
      serviceFeePercent: 0.0, // Prime membership
      minimumOrder: 50.00,
      active: true,
    },
    {
      name: 'Walmart+',
      slug: 'walmart-plus',
      type: 'grocery',
      logo: '/platforms/walmart-plus.png',
      website: 'https://www.walmart.com/plus',
      apiEnabled: false,
      appScheme: 'walmart://',
      iosAppId: '338137227',
      androidPackage: 'com.walmart.android',
      deliveryFeeMin: 0.00,
      deliveryFeeMax: 9.95,
      serviceFeePercent: 0.0, // Membership-based
      minimumOrder: 35.00,
      active: true,
    },
    {
      name: 'Skip The Dishes',
      slug: 'skip-the-dishes',
      type: 'restaurant',
      logo: '/platforms/skipthedishes.png',
      website: 'https://www.skipthedishes.com',
      apiEnabled: false,
      appScheme: 'skipthedishes://',
      iosAppId: '882168087',
      androidPackage: 'com.skipthedishes.consumer',
      deliveryFeeMin: 1.99,
      deliveryFeeMax: 7.99,
      serviceFeePercent: 11.0,
      minimumOrder: 15.00,
      active: true,
    },
    {
      name: 'Deliveroo',
      slug: 'deliveroo',
      type: 'both',
      logo: '/platforms/deliveroo.png',
      website: 'https://www.deliveroo.com',
      apiEnabled: false,
      appScheme: 'deliveroo://',
      iosAppId: '1001501844',
      androidPackage: 'com.deliveroo.orderapp',
      deliveryFeeMin: 0.99,
      deliveryFeeMax: 5.99,
      serviceFeePercent: 10.0,
      minimumOrder: 10.00,
      active: true,
    },
    {
      name: 'Just Eat',
      slug: 'just-eat',
      type: 'restaurant',
      logo: '/platforms/justeat.png',
      website: 'https://www.just-eat.co.uk',
      apiEnabled: false,
      appScheme: 'justeat://',
      iosAppId: '566347057',
      androidPackage: 'com.justeat.app',
      deliveryFeeMin: 0.00,
      deliveryFeeMax: 4.99,
      serviceFeePercent: 8.0,
      minimumOrder: 15.00,
      active: true,
    },
    {
      name: 'Menulog',
      slug: 'menulog',
      type: 'restaurant',
      logo: '/platforms/menulog.png',
      website: 'https://www.menulog.com.au',
      apiEnabled: false,
      appScheme: 'menulog://',
      iosAppId: '368037948',
      androidPackage: 'com.menulog.m',
      deliveryFeeMin: 0.00,
      deliveryFeeMax: 6.99,
      serviceFeePercent: 10.0,
      minimumOrder: 20.00,
      active: true,
    },
  ];

  for (const platform of platforms) {
    await prisma.deliveryPlatform.upsert({
      where: { slug: platform.slug },
      update: platform,
      create: platform,
    });
  }

  console.log(`✅ Seeded ${platforms.length} delivery platforms`);
}
